# Change these first
owner: TogijorOK # Your GitHub organization or username, where this repository lives
repo: Monitor_WEB # The name of this repository

sites:
  
  - name: Sitio WEB Corporativo
    url: https://www.aysa.com.ar
    __dangerous__disable_verify_peer: true
  - name: Autoservicio (Ciberseguridad)
    url: https://autoservicio.aysa.com.ar/authorization.do
  - name: Campus
    url: https://campus.aysa.com.ar
  - name: Intranet
    url: https://intranet.aysa.com.ar
  - name: Servicedesk
    url: https://servicedesk.aysa.com.ar
  - name: Turnera
    url: https://turnosonline.aysa.com.ar
  - name: Correo (OWA)
    url: https://mail.aysa.com.ar
    icon: https://github.com/TogijorOK/Monitor_WEB/blob/b48bd30ea49f527326e27bcbcccb347e2b7e8fe0/assets/ico_outlook.png
  - name: Licitaciones
    url: https://aysa.com.ar/proveedores/licitaciones
    __dangerous__disable_verify_peer: true
  - name: Tarifa social
    url: https://aysa.com.ar/usuarios/Tarifa-Social/tarifa_social
    __dangerous__disable_verify_peer: true
    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Monitor_WEB
  logoUrl: https://aysa.com.ar/media-library/imagenes_inicio/logo.png
  name: Soporte Aplicativos
  introTitle: "**MONITOR-Servicios WEB**"
  introMessage: Dirección Tecnología de la Información - Gerencia de Servicios Informáticos
  navbar:
    - title: Estado de sevicios web
      href: /
    - title: AySA S.A.
      href: https://www.aysa.com.ar
    - title: Powered by
      href: https://github.com/TogijorOK

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
